feat: Add postgresql connector
Multiwoven/multiwoven-integrations pull request #72
Opened 2024-02-17 16:40 UTC by karthik-sivadas

## Description
feat: Add postgresql connector

## Related Issue
https://github.com/Multiwoven/multiwoven-integrations/issues/52

## Type of Change
- [x] New Connector (Destination or Source Connector)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would impact existing functionality)
- [ ] Documentation update
- [ ] Chore
  
## How Has This Been Tested?
Wrote unit test and tested it locally

## Checklist:
- [x] Ensure a branch name is prefixed with `feature`, `bugfix`, `hotfix`, `release` or `chore` followed by `/` and branch name e.g `feature/add-salesforce-connector`
- [x] Added the new connector in rollout.rb
- [x] Have you updated the version number of the gem?
- [ ] Have you ensured that your changes for new connector are documented in the [docs repo](https://github.com/Multiwoven/docs) or relevant documentation files?
- [ ] Have you updated the run time dependency in multiwoven-integrations.gemspec if new gems are added

2024-02-17 17:03 UTC, subintp requested changes

2024-02-17 17:03 UTC, subintp commented on lib/multiwoven/integrations/source/postgresql/client.rb
> +  module Postgresql
Don't make the postgresql depend upon redshift. We can re-use the code. We don't know how these connector's will evolve eg: Introducing oauth as authentication.

2024-02-17 17:03 UTC, subintp commented on assets/images/connectors/postgresql.svg
Add the icon inside the connector.

2024-02-19 03:54 UTC, karthik-sivadas commented on assets/images/connectors/postgresql.svg
Changed

2024-02-19 11:07 UTC, subintp approved these changes

2024-02-19 11:08 UTC, merged