feat: Add hubspot destination connector
Multiwoven/multiwoven-integrations pull request #77
Opened 2024-02-28 16:26 UTC by karthik-sivadas

## Description
feat: Add hubspot destination connector

## Related Issue

## Type of Change
- [x] New Connector (Destination or Source Connector)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would impact existing functionality)
- [ ] Documentation update
- [ ] Chore
  
## How Has This Been Tested?
Wrote specs and tested it locally

## Checklist:
- [x] Ensure a branch name is prefixed with `feature`, `bugfix`, `hotfix`, `release` or `chore` followed by `/` and branch name e.g `feature/add-salesforce-connector`
- [x] Added the new connector in rollout.rb
- [x] Have you updated the version number of the gem?
- [x] Have you ensured that your changes for new connector are documented in the [docs repo](https://github.com/Multiwoven/docs) or relevant documentation files?
- [x] Have you updated the run time dependency in multiwoven-integrations.gemspec if new gems are added

2024-02-29 11:00 UTC, subintp requested changes

2024-02-29 11:00 UTC, subintp commented on lib/multiwoven/integrations/destination/hubspot/client.rb
> +            failure_status(e)
Log error message with stack trace

2024-02-29 11:00 UTC, subintp commented on lib/multiwoven/integrations/destination/hubspot/client.rb
> +          def process_record(stream, record)
what is the use of this method ?

2024-02-29 11:00 UTC, subintp commented on lib/multiwoven/integrations/destination/hubspot/client.rb
> +            eval("@client.crm.#{stream_name}.basic_api.#{@action}(simple_public_object_input_for_create: #{args})") # rubocop:disable Security/Eval, Style/EvalWithLocation
Not able to understand. Add a comment on how this line works

2024-03-01 04:10 UTC, karthik-sivadas commented on lib/multiwoven/integrations/destination/hubspot/client.rb
> +          def process_record(stream, record)
No special use will remove this

2024-03-01 04:19 UTC, karthik-sivadas commented on lib/multiwoven/integrations/destination/hubspot/client.rb
> +            eval("@client.crm.#{stream_name}.basic_api.#{@action}(simple_public_object_input_for_create: #{args})") # rubocop:disable Security/Eval, Style/EvalWithLocation
Changed the eval

2024-03-01 05:28 UTC, afthabvp commented on lib/multiwoven/integrations/destination/hubspot/config/catalog.json
> +  "request_rate_limit": 100000,
rate limit values are the real numbers for hubspot

2024-03-01 06:02 UTC, afthabvp approved these changes
LGTM

2024-03-01 06:04 UTC, subintp approved these changes

2024-03-01 06:04 UTC, merged