feat: Add google sheets
Multiwoven/multiwoven-integrations pull request #89
Opened 2024-03-08 03:50 UTC by karthik-sivadas

## Description

## Related Issue

## Type of Change
- [ ] New Connector (Destination or Source Connector)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would impact existing functionality)
- [ ] Documentation update
- [ ] Chore
  
## How Has This Been Tested?

## Checklist:
- [ ] Ensure a branch name is prefixed with `feature`, `bugfix`, `hotfix`, `release` or `chore` followed by `/` and branch name e.g `feature/add-salesforce-connector`
- [ ] Added the new connector in rollout.rb
- [ ] Have you updated the version number of the gem?
- [ ] Have you ensured that your changes for new connector are documented in the [docs repo](https://github.com/Multiwoven/docs) or relevant documentation files?
- [ ] Have you updated the run time dependency in multiwoven-integrations.gemspec if new gems are added

2024-03-11 06:21 UTC, afthabvp commented on lib/multiwoven/integrations/destination/google_sheets/client.rb
> +          def generate_json_schema(column_names, sheet_name)
The MAX_CHUNK_SIZE variable is set to 10,000, indicating the maximum number of records that can be processed in a single batch.
 If Google Sheets supports batch operations add these fields in your stream
 
 `   "batch_support": true,
      "batch_size": 10000,`

2024-03-11 06:21 UTC, afthabvp commented on lib/multiwoven/integrations/destination/google_sheets/client.rb
> +              supported_sync_modes: %w[full_refresh incremental]
full_refresh not yet implemented
please remove it

2024-03-11 06:24 UTC, afthabvp commented on lib/multiwoven/integrations/destination/google_sheets/client.rb
> +          GOOGLE_SHEETS_SCHEMA_URL = "http://json-schema.org/draft-07/schema#"
It's a JSON schema URL. Move it to the constants so we can use it.

2024-03-11 09:40 UTC, subintp requested changes

2024-03-11 09:50 UTC, karthik-sivadas commented on lib/multiwoven/integrations/destination/google_sheets/config/meta.json
> +    "documentation_url": "https://docs.multiwoven.com/destinations/productivity-tools/google-sheets-service-account",
Have created a draft PR need minor changes. Will update it. The link will be same.

2024-03-11 09:50 UTC, karthik-sivadas commented on lib/multiwoven/integrations/destination/google_sheets/client.rb
> +          GOOGLE_SHEETS_SCOPE = "https://www.googleapis.com/auth/drive"
We need to pass the scope for google API. I will add a comment with link

2024-03-12 09:47 UTC, subintp approved these changes

2024-03-12 09:47 UTC, merged